export const FETCH_TEMPERATURE_LIST_START = 'FETCH_TEMPERATURE_LIST_START';
export const FETCH_TEMPERATURE_LIST_SUCCESS = 'FETCH_TEMPERATURE_LIST_SUCCESS';
export const FETCH_TEMPERATURE_LIST_FAIL = 'FETCH_TEMPERATURE_LIST_FAIL';

export const FETCH_PRECIPITAION_LIST_START = 'FETCH_PRECIPITAION_LIST_START';
export const FETCH_PRECIPITAION_LIST_SUCCESS = 'FETCH_PRECIPITAION_LIST_SUCCESS';
export const FETCH_PRECIPITAION_LIST_FAIL = 'FETCH_PRECIPITAION_LIST_FAIL';
